### ISSUE TITLE
spacecube

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/hexxytest3#37]
https://modrinth.com/mod/spacecube

**Comment by abilliontrillionstars** [comment]
it looks like a small unpolished mod, and if hexdim updates it would be a more fitting replacement. it also has overlap with AE2 Spatial Storage, but I'm no expert on the differences between these two

**Comment by walksanatora** [comment]
compact machines are nice. just gotta figure out what ports it has. and if it has JADE integration
