### ISSUE TITLE
hextweaks

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/hexxytest3#46]
https://modrinth.com/mod/hextweaks
from https://github.com/ChloeTax/hexxytest3/issues/43

**Comment by SupernovaXTS** [comment]
when i tested it, it appeared to conflict with complexhex

**Comment by SupernovaXTS** [comment]
nope tested it a few weeks ago

**Comment by walksanatora** [comment]
yeah I released yesterday after merging a PR to fix 1.20 release

**Comment by Twisted-Code** [comment]
Oh yeah, hextweaks has the fancy new rituals in 1.20 doesn't it? E.g. the one to speed up titration?
Nice.

**Comment by SupernovaXTS** [comment]
It also has the turtle and pocket computer casting
