### ISSUE TITLE
spice of life valheim edition

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/hexxytest3#9]
https://modrinth.com/mod/spice-of-life-valheim-edition

...in Valheim, you have three food slots which you must fill. Eating a food item will fill a slot, giving you the benefits of increased health and regeneration until it runs out. You then cannot eat that food again until the timer runs out (or almost runs out).

https://discord.com/channels/936370934292549712/1312594452409221222/1318534493065187338

**Comment by Stick404** [comment]
I would be personally against this mod, mostly because I am not a fan of mods that force you to eat differently in the game. However, a mod like Spice of Life: Carrot Edition would be better; because imo its better to reward more diverse eating, then to punesh limited eating
